//
//  LoginModels.swift
//  Bank-CleanSwift
//
//  Created by Scott Takahashi on 31/07/20.
//  Copyright (c) 2020 Scott Takahashi. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Login
{
  // MARK: Use cases
  
    struct Request {
        let userName: String
        let password: String
    }
    
    struct UserResponse {
        let userAccount: UserAccount
    }
    
    struct ErrorResponse {
        let error: BankError
    }
    
    struct UserNameResponse {
        let userName: String
    }
    
    struct UserViewModel {
        let userAccount: UserAccount
    }
    
    struct UserNameViewModel {
        let userName: String
    }
    
    struct ErrorViewModel {
        let error: BankError
    }
}
