//
//  LoginViewController.swift
//  Bank-CleanSwift
//
//  Created by Scott Takahashi on 31/07/20.
//  Copyright (c) 2020 Scott Takahashi. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol LoginDisplayLogic: class
{
  func displaySomething(viewModel: Login.ViewModel)
}

class LoginViewController: UIViewController, LoginDisplayLogic {
    
    private let loginButtonRadius: CGFloat = 4
    
    @IBOutlet private(set) weak var userTextField: UITextField!
    @IBOutlet private(set) weak var passwordTextField: UITextField!
    @IBOutlet private(set) weak var loginButton: UIButton!
    
    var interactor: LoginBusinessLogic?
    var router: (NSObjectProtocol & LoginRoutingLogic & LoginDataPassing)?

    override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?) {
        super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
        self.setup()
    }

    required init?(coder aDecoder: NSCoder) {
        super.init(coder: aDecoder)
        self.setup()
    }
    
    override func viewDidLoad() {
        super.viewDidLoad()
        self.setupView()
        doSomething()
    }
  

}

// MARK: private func
extension LoginViewController {
      
    private func setup()  {
        let viewController = self
        let interactor = LoginInteractor()
        let presenter = LoginPresenter()
        let router = LoginRouter()
        viewController.interactor = interactor
        viewController.router = router
        interactor.presenter = presenter
        presenter.viewController = viewController
        router.viewController = viewController
        router.dataStore = interactor
    }
        
    private func setupView() {
        self.userTextField.placeholder = "login.userTextField.placeholder".localized()
        self.passwordTextField.placeholder = "login.passwordTextField.placeholder".localized()
        self.loginButton.setTitle("login.loginButton.text".localized(), for: .normal)
        self.loginButton.layer.cornerRadius = loginButtonRadius
    }

    // MARK: Do something

    //@IBOutlet weak var nameTextField: UITextField!

    func doSomething()
    {
        let request = Login.Request()
        interactor?.doSomething(request: request)
    }

    func displaySomething(viewModel: Login.ViewModel)
    {
    //nameTextField.text = viewModel.name
    }
    
}
