//
//  LoginRouter.swift
//  Bank-CleanSwift
//
//  Created by Scott Takahashi on 31/07/20.
//  Copyright (c) 2020 Scott Takahashi. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol LoginRoutingLogic
{
    func goToStatements()
}

protocol LoginDataPassing
{
  var dataStore: LoginDataStore? { get }
}

class LoginRouter: NSObject, LoginRoutingLogic, LoginDataPassing {
    weak var viewController: LoginViewController?
    var dataStore: LoginDataStore?
  
    func goToStatements() {
        let statmentsViewController = StatementsViewController()
        var statmentsDataStore = statmentsViewController.router?.dataStore
        statmentsDataStore?.userAccount = dataStore?.user
        viewController?.show(statmentsViewController, sender: nil)
    }
  
}
